version: 2.1

defaults: &defaults
    docker:
      - image: docker:17.11.0-ce-git
        environment:
          ENV: $BASH_ENV

install_dependency: &install_dependency
          name: Installation of build and deployment dependencies.
          command: |
            apk update
            apk add --no-cache bash openssl curl
            apk upgrade
            apk add --no-cache jq py-pip sudo
            sudo pip install awscli --upgrade
            
install_deploysuite: &install_deploysuite
          name: Installation of install_deploysuite.
          command: |
            git clone --branch dev_comm https://github.com/topcoder-platform/tc-deploy-scripts ../buildscript
            cp ./../buildscript/master_deploy.sh .
            cp ./../buildscript/buildenv.sh .
            cp ./../buildscript/awsconfiguration.sh .
restore_cache_settings_for_build: &restore_cache_settings_for_build
  key: docker-node-modules-v3-{{ checksum "package-lock.json" }}

save_cache_settings: &save_cache_settings    
  key: docker-node-modules-v3-{{ checksum "package-lock.json" }}  
  paths:
    - node_modules      

build_docker_image: &build_docker_image
          name: Build of Docker image
          command: |
            source buildenvvar
            ./build.sh
jobs:
  # Build & Deploy against development backend
  "build-dev":
    <<: *defaults
    steps:
      # Initialization.
      - checkout
      - setup_remote_docker
      - run: *install_dependency
      - run: *install_deploysuite
      # Restoration of node_modules from cache.
      - restore_cache: *restore_cache_settings_for_build
      # Build of Docker image.
      - run: 
          name: "configuring environment"
          command: |
            ./awsconfiguration.sh DEV
            ./buildenv.sh -e DEV -b dev_skills_etl_buildvar,dev_skills_etl_deployvar      
      - run: *build_docker_image
      # Caching node modules.
      - save_cache: *save_cache_settings
      # Deployment.
      - deploy:
          name: Running MasterScript
          command: |
            source buildenvvar
            source awsenvconf
            ./master_deploy.sh -d ECS -e DEV -t latest -s dev_skills_etl_taskvar -i skills-etl

  
  # Build & Deploy against production backend
  "build-prod":
    <<: *defaults
    steps:
      # Initialization.
      - checkout
      - setup_remote_docker
      - run: *install_dependency
      - run: *install_deploysuite
      # Restoration of node_modules from cache.
      - restore_cache: *restore_cache_settings_for_build
      - run: 
          name: "configuring environment"
          command: |
            ./awsconfiguration.sh PROD
            ./buildenv.sh -e PROD -b prod_skills_etl_buildvar,prod_skills_etl_deployvar
      # Build of Docker image.
      - run: *build_docker_image
      # Caching node modules.
      - save_cache: *save_cache_settings   
      # Deployment.
      - deploy:
          name: Running MasterScript
          command: |
            source awsenvconf
            source buildenvvar
            ./master_deploy.sh -d ECS -e PROD -t latest -s prod_skills_etl_taskvar -i skills-etl -p FARGATE

workflows:
  version: 2
  build:
    jobs:
      # Development builds are executed on "new-develop" branch only.
      - "build-dev":
          context : org-global
          filters:
            branches:
              only:
                - develop
                -  circleci-project-setup     
      # Production builds are exectuted 
      # when PR is merged to the master
      # Don't change anything in this configuration
      # That might trigger wrong branch to be 
      # deployed on the production
      # master branch.
      - "build-prod":
          context : org-global      
          filters:
            branches:
              only:
                - master    
      # Simple testing is executed for any branch other than "develop" and
      # "master".
     